---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: applications
  namespace: flux-system
spec:
  targetNamespace: food2gether
  dependsOn:
    - name: dev-infra
  interval: 1m0s
  path: ./applications
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 2m0s
  wait: true