---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: operators
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./operators
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 2m0s
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: operators-config
        optional: true
      - kind: Secret
        name: operators-secrets
        optional: true
