---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: emberstack
  namespace: reflector
spec:
  interval: 1m0s
  url: https://emberstack.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: flux-system
spec:
  chart:
    spec:
      chart: reflector
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: emberstack
      version: 7.1.288
  interval: 10m0s
