# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  type: ClusterIP
  ports:
  - name: postgresql
    protocol: TCP
    port: 5432
    targetPort: 5432
---
