---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  interval: 1m0s
  url: https://oauth2-proxy.github.io/manifests
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  chart:
    spec:
      chart: oauth2-proxy
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: oauth2-proxy
      version: 7.11.0
  interval: 1m0s
  values:
    config:
      clientID: "${oauth2_clientID}"
      clientSecret: "${oauth2_clientSecret}"
      cookieSecret: "${oauth2_cookieSecret:=Qhf9cr4Ka0KppRneM12crmu-GN6bP0FyfhLzyf_BjYc=}"

      configFile: |
        provider = "${oauth2_provider}"
        email_domains = ${oauth2_email_domains:=["*"]}
        redirect_url = "${oauth2_redirect_url:=}"
        code_challenge_method = "${oauth2_code_challenge_method:=}"
        oidc_issuer_url = "${oauth2_oidc_issuer_url:=}"
        upstreams = [ "file:///dev/null" ]
        set_xauthrequest = true
        set_authorization_header = true
        pass_access_token = true
        scope = "openid email profile read:user"
        api_routes = "/api/*"
    #    custom_templates_dir = "/data/custom-templates}"
    ingress:
      enabled: true
      hosts:
        - '' # This matches any host (same as '*'; no host set)
      className: nginx
      path: /oauth2/
      pathType: Prefix

      # extraVolumes:
      #   - name: oauth2-proxy-templates
      #     configMap:
      #       name: oauth2-proxy-templates
      # 
      # extraVolumeMounts:
      #   - name: oauth2-proxy-templates
      #     mountPath: /data/custom-templates
      #     readOnly: true

      # extraObjects:
      #   - apiVersion: v1
      #     kind: ConfigMap
      #     metadata:
      #       name: oauth2-proxy-templates
      #       namespace: oauth2-proxy
      #     data:
      #       sign_in.html: |
      #         <html>
      #           <head>
      #             <title>Sign In</title>
      #           </head>
      #           <body>
      #             <h1>Sign In</h1>
      #             <form method="post">
      #               <input type="text" name="email" placeholder="Email" />
      #               <input type="password" name="password" placeholder="Password" />
      #               <input type="submit" value="Sign In" />
      #             </form>
      #           </body>
      #         </html>
      #       error.html: |
      #         <html>
      #           <head>
      #             <title>Error</title>
      #           </head>
      #           <body>
      #             <h1>Error</h1>
      #             <p>{{ .Error }}</p>
      #           </body>
      #         </html>
        