apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - flux-system
  - components

patches:
  - target:
      group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
      name: flux-system
      namespace: flux-system
    patch: |
      - op: add
        path: /spec/wait
        value: true