apiVersion: v1
kind: Secret
metadata:
  name: database
type: Opaque
stringData:
  # Defaulting to credentials in dev-infra/postgresql/deployment.yaml file
  username: ${database_username:username}
  password: ${database_password:password}
  database: ${database_name:food2gether}
  host: ${database_host:postgresql.food2gether.svc.cluster.local}
  port: ${database_port:5432}
---