# https://kubernetes.io/docs/concepts/services-networking/ingress/
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: food2gether
  namespace: food2gether
spec:
  rules:
  - http:
      paths:
      - path: /api/v1/restaurants
        pathType: Prefix
        backend:
          service:
            name: restaurant-service
            port:
              number: 80
      - path: /api/v1/profiles
        pathType: Prefix
        backend:
          service:
            name: profile-service
            port:
              number: 80
      - path: /api/v1/sessions
        pathType: Prefix
        backend:
          service:
            name: session-service
            port:
              number: 80
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: api-fallback-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
---