apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: food2gether
  namespace: food2gether
  annotations:
    # auth-url will be called by oauth2-proxy inside the cluster. There is no need to resolve this
    # via the external api
    nginx.ingress.kubernetes.io/auth-url: "http://oauth2-proxy.oauth2-proxy.svc.cluster.local/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "http://$host/oauth2/login?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-User, X-Auth-Request-Email, Authorization, X-Forwarded-Access-Token"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api/v1/restaurant
        pathType: Prefix
        backend:
          service:
            name: restaurant-service
            port:
              number: 80
      - path: /api/v1/auth
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 80
      - path: /api/v1/profile
        pathType: Prefix
        backend:
          service:
            name: profile-service
            port:
              number: 80
      - path: /api/v1/session
        pathType: Prefix
        backend:
          service:
            name: session-service
            port:
              number: 80
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: api-fallback-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
---