apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: postgresql
spec:
  inheritedMetadata:
    # Workaround to sync base-auth secret to app namespace
    # Issue: https://github.com/cloudnative-pg/cloudnative-pg/issues/5883
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: 'true'
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: 'food2gether'
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: 'food2gether'
  # Configure stoage for production
  # TODO: Configure observability at some time
  # We might wont to add a hidden credential secret at some time
  instances: 1
  storage:
    size: 5Gi

